name: update api docs

on:
  issues:
    types: [ opened ]

permissions: write-all

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up and Run script
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install requests
      - run: python3 ./scripts/update_swagger.py ${{ secrets.GH_TOKEN }}

      - name: Commit to repository
        run: |
          git config --global user.email "wwan13@naver.com"
          git config --global user.name "wwan13"
          git add .
          git commit -m "docs : update api docs"
          git push origin main